---
title: "S&DS 425/625 Report Template"
author: "Name(s)"
date: "Date"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo   =FALSE,      ## show or suppress the code
                      include=TRUE ,      ## show or suppress the output
                      message=FALSE,      ## omit messages generated by code
                      warning=FALSE,      ## omit warnings generated by code
                      comment=NA,         ## removes the ## from in front of outputs
                      fig.align="center", ## centers all figures
                      fig.height = 5,     ## set the default height
                      fig.weight = 5      ## set the default width
                      )
```

## Abstract



## Executive Summary



## Introduction

In this project, we attempt to improve USA Gymnastics' team selection criteria for the Summer Olympic Games. For the 2020 Tokyo Olympics (held in 2021), the US Olympic and Paralympic Committee (USOPC) selected the men's team solely to maximize the chance of winning the team gold medal. Given the quality of opposing men's gymnastics teams, such a goal wasn't entirely feasible, and optimizing for the team event came at the expense of single-event specialists who could've won medals in the individual events. We improve this methodology by creating an interactive tool that allows the USOPC to make data-based selection decisions while prioritizing certain events or medal types. It also provides a breakdown of expected medal count in each event for each combination of gymnasts, allowing the user to compare five-person teams and their expected scores side by side.

We used a dataset that contains the full results of top gymnastics competitions in the 2022-23 season. Each athlete is listed with their name, country, competition name, competition date, apparatus, and score. Since the dataset includes the most prestigious events, such as the World Championships, U.S. National Championships, European Championships, and Commonwealth Games, we had with sufficient data for all of the world's top gymnasts in the season.

Section 2 contains data exploration and visualization, which reveals that many gymnasts were present in the data under multiple names, requiring consolidation before further analysis. In Section 3, we build several different predictive models and find that each country in the Olympic team event has between 6 and 15 athletes to choose from who could reasonably contribute to an "optimal" group under our criteria. We discuss the results of the model, including the presence of single-apparatus specialists on the USA men's team, in Section 4. Finally, we discuss conclusions, recommendations and ideas for future work in Section 5.

## Data exploration and visualization


## Modeling/Analysis

Our team selection model consisted of running a series of simulations for each athlete in order to predict their medal outcome. In order to ensure the medal predictions for Team USA were reliable, we followed the same team selection and simulation procedures for all countries' competitors.

This procedure began with grouping together each athlete's scores and obtaining their personal mean and standard deviation from each apparatus. We chose to exclude the athletes within the top 15% highest variance for some apparatus to account for those who might be prone to falling or other risks.

We also approximated each athlete's individual all-around score by totaling up their averages for each of the 4 apparatuses for women and each of the 6 apparatuses for men.

In order to speed up simulations, we chose to limit our athlete pool to only athletes who were either in the top 3 all-around for their country or within the top 3 for at least one apparatus for their country, based on their averaged scores. Due to the large amount of simulations necessary for our team selection, it was important to us to limit our pool of athletes as best we could in the interest of time. Our reasoning was if an athlete was not in the top 3 for any event within their own country, it would be unlikely for them to get a medal in an international competition. This resulted in somewhere between 6 and 15 potential athletes to consider for each of the competing countries.

\begin{table}[h]
    \centering
    \caption{Number of athletes per country (men)}
    \begin{tabular}{|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        CAN & CHN & ESP & GBR & GER & ITA & JPN & NED & SUI & TUR & UKR & USA \\
        \hline
        10  & 11  & 8   & 11  & 10  & 13  & 15  & 6   & 11  & 8   & 8   & 14  \\
        \hline
    \end{tabular}
\end{table}

\begin{table}[h]
    \centering
    \caption{Number of athletes per country (women)}
    \begin{tabular}{|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        AUS & BRA & CAN & CHN & FRA & GBR & ITA & JPN & KOR & NED & ROU & USA \\
        \hline
        9   & 7   & 9   & 14  & 11  & 7   & 8   & 12  & 7   & 9   & 7   & 10  \\
        \hline
    \end{tabular}
\end{table}



In each round of simulations, we began by initializing the teams randomly by selecting five athletes from each country.

Then, one at a time, we chose one of the 12 countries with a team and went through every possible combination of 5 athletes, keeping the other 11 countries' teams fixed. In each round of the simulation, we used a normal approximation using their personal mean and standard deviation for each event for all of the athletes to approximate a potential score in competition. The team round was simulated by choosing the best 3 athletes per apparatus per country and summing up their scores. We were able to thus approximate medal placements by ranking the simulated scores for each event. Random samples were drawn 99 times for each group of athletes in order to account for variability in our random samples. By taking the average, we calculated the expected number of gold, silver, and bronze medals for the team, breaking it into categories of "team round", "individual all around," and "individual apparatus."

Finally, the expected medals were multiplied by the provided weights and the "optimal team" was chosen for the selected country based on which combination of five athletes provided the highest weighted total. This optimal team was passed back into the roster of teams so when the next country was passed through we would make sure they were competing against the best possible athletes. For this, we made sure to pass through each country twice in order to get as close as possible to simulating a real competition between the top athletes. This same procedure was repeated for both men and women.

A key part of our analysis was to weight events and medals based on various criteria. In the interactive Shiny app, the user is given the opportunity to show the best team based on what they value the most.

Sliders are provided to weight each type of event ("team round", "individual all around," and "individual apparatus") between 0, 1, and 2, and clickable buttons let the user choose between "maximize total medals," where gold, silver, and bronze are weighted equally, "maximize gold medals", where silver and bronze medals are not considered, and "prefer gold medals," where gold medals are weighted higher than silver or bronze. This allows for an added degree of interactivity when choosing which team is preferred.

This means that all of the simulations had to be run multiple times to account for each possible weightings.

## Visualization and interpretation 

Once the simulations were run, one of the key features of this analysis was putting together our findings into an interactive shiny app. The outcome allows users to choose their own custom preferences for weights and explore how different teams might perform differently in competition.
This allows for a very thorough exploration of how different groups of athletes will perform.

The shiny app has two main tabs. For each tab, the user is able to pick whether they want to consider men or women, and which country they would like to look at. These preferences carry over when the tab is changed.

The first tab is called "Generate Teams," which gives the user a clickable panel to choose their preferences for medals and which events they would like to prioritize. Once the weight options are chosen, the right panel auto-populates with a list of the five athletes that will give the best performance under those criteria and the number of gold, silver, and bronze medals this particular team would be expected to win. 

The second tab, entitled "Compare Teams" gives the user a bit more flexibility in team selection. Here, we can compare side-by-side how two different groups of five athletes would be expected to perform. This has huge potential - we can see clearly how important particular athletes are to their teams, and can consider alternative options in case an athlete gets injured or decides not to compete.  

## Conclusions and recommendations



